name: portifolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.local
    - assets/images/
    - assets/icons/
    - assets/langs/en.json
    - assets/langs/pt_BR.json

  fonts: 
    - family: Retro
      fonts:
        - asset: fonts/Fixedsys_Excelsior.ttf
    - family: Retro2
      fonts:
        - asset: fonts/MSW98UI-Regular.ttf
    - family: Retro2B
      fonts:
        - asset: fonts/MSW98UI-Bold.ttf